service: notification-notifier
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.12
  region: sa-east-1
  timeout: 15
  memorySize: 256
  environment:
    EMAIL_HOST: ${env:EMAIL_HOST}
    EMAIL_PORT: ${env:EMAIL_PORT}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    EMAIL_FROM: ${env:EMAIL_FROM}
    CUSTOMER_SERVICE_URL: ${env:CUSTOMER_SERVICE_URL}

functions:
  notifier:
    handler: notifier/handler.handler

plugins:
  - serverless-localstack

custom:
  localstack:
    stages: [local]
    host: http://localhost
    edgePort: 4566
    autostart: false
